const List<String> names4D = [
  "University of Texas at Dallas",
  "Engineering & Computer Science West",
  "Plinth",
  "UT Dallas Combined",
  "S1",
  "S2",
  "S3",
  "S6",
  "S5",
  "S4",
  "Lot J",
  "I2",
  "Lot Q",
  "Lot M East",
  "Parking Structure 4",
  "Lot H",
  "Phase 8 pool",
  "Cecil and Ida Green Center",
  "Lot N",
  "2",
  "12",
  "4",
  "6",
  "11",
  "9",
  "3",
  "7",
  "Edith O'Donnell Arts and Technology Building",
  "Engineering & Computer Science South",
  "Residence Hall South",
  "Residence Hall North",
  "Residence Hall Northwest",
  "Lot A",
  "Lot B",
  "Lot C",
  "Lot D",
  "Residence Hall Southwest",
  "Physics Building",
  "Lot R",
  "Lot P",
  "Lot G",
  "35",
  "36",
  "33",
  "Lot U",
  "10",
  "Phase 3 pool",
  "65",
  "66",
  "67",
  "59",
  "56",
  "55",
  "54",
  "53",
  "57",
  "58",
  "Phase 1 pool",
  "Energy Plant",
  "46",
  "43",
  "38",
  "40",
  "41",
  "39",
  "5",
  "Clubhouse",
  "45",
  "51",
  "48",
  "49",
  "50",
  "61",
  "62",
  "63",
  "University Village Leasing Office",
  "15",
  "16",
  "21",
  "19",
  "20",
  "17",
  "18",
  "22",
  "14",
  "Phase 2 Clubhouse",
  "Phase 2 pool",
  "Visitors Center",
  "Arts and Humanities 1",
  "Arts and Humanities 2",
  "Classroom Building 3",
  "Classroom Bldg 1",
  "Classroom Bldg 2",
  "Parking Structure 3",
  "Recreation Center West",
  "Dining Hall West",
  "Res Lot North",
  "Residence Lot Northwest",
  "Lot M West",
  "Holly Hedgerows",
  "Entry Mound",
  "Lot E",
  "Parking Structure 1",
  "Chess Plaza",
  "Reflection Pools",
  "Green Parking",
  "Lot T",
  "Lot T Overflow",
  "Engineering & Computer Science North",
  "Student Union Food Court",
  "Callier Richardson Addtion",
  "Facilities Management",
  "S9",
  "S10",
  "S8",
  "S7",
  "Davidson-Gundy Alumni Center",
  "UT Dallas Alumni Disc Golf Course",
  "Gazebo",
  "Gazebo Park",
  "The Lawn",
  "The Plinth",
  "Lot S",
  "Generators",
  "Physics Annex",
  "Bus Stop UTD",
  "Residence Hall West",
  "Science Building",
  "TI Plaza",
];
